
language: rust
cache: cargo

env:
  global:
    - PROJECT_NAME=flowgger
    - MAKE_DEB=yes
    - DEB_MAINTAINER="Frank Denis <github@pureftpd.org>"
    - DEB_DESCRIPTION="A fast, simple and lightweight data collector"

matrix:
  include:
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
      env: FEATURES="coroutines ecdh"
      dist: trusty
      sudo: required
      addons:
        apt:
          packages: &std_unknown_linux_gnu
            - libsnappy-dev
            - libssl-dev

    - os: linux
      rust: stable
      dist: trusty
      sudo: required
      env: TARGET=x86_64-unknown-linux-gnu
      env: FEATURES="ecdh"
      addons:
        apt:
          packages: *std_unknown_linux_gnu

  allow_failures:
    - os: linux
      rust: stable
      dist: trusty
      sudo: required
      env: TARGET=x86_64-unknown-linux-gnu
      env: FEATURES="ecdh"

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: 0Y8ZXOJaNJJ5/0IRcXyNIOJK4EICQDRtaB/E+pboNUchJn9fThGMQc2QtZaGddBNrnuHsftBFM7mWXJvZ2H9YGgbBl1N6Z2y33vawSPgzTnfz0CZRJfX1Gl6IdtDH9zvlblHI1aE4eJ6lAu0q8VQ874CBPxoIlzU9jArOTdvyPT+8t64Y0K240trfqrm0NHloUbZtm+HeRJqoK1RKE4kdrpESIVMyyq67fM9T0VqLg+x3OHeQ/itFnZpjqtVtj9WhZeKM6iTNLQT+vLpRAvq8w6sv1WeCMYAqdXUL7jQnVaI+MiepC9z8OoF0ZAYes0I+3aaNsgMHiuwkW+nDUcQp5XLDW3oCq/uST4pN2ki/AJPy4UUUx++xb8SgtKE4wzBGbT0u5yO9JkIPxJZRLy+E0IvTlqVEZL/tvnI09JQQmzgDdP1hCcxpxBBm4xLi/2qSHIJIMUbb92DRwOrTii34+C0oa1UZKh2P/ceCtLNOlOCmFAcWE9uAxjEGP903mmgbixj8xBbyuROedHIMxag0Jr9Tdoi0hsVdhOEss4JjNKf7ayjepRIw5lNFjxk+jgB+Om0J3vQ+i83LxX1a0b9YV+KJUtWz/CV43mwYhF+jh2GAMe0/cvNCbFT4au0SW2FKDvV/00AJ5tPGimVXNe0e+AUqjbJ2sRpylIQw1Mfl6Y=
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: change
