[package]
name = "flowgger"
version = "0.0.2"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
chrono = "*"
log = "*"
serde = "*"
serde_json = "*"
toml = "*"
clippy = "*"

[dependencies.kafka]
git = "https://github.com/jedisct1/kafka-rust.git"

[dependencies.openssl]
version = "*"
features = ["tlsv1_2", "tlsv1_1"]

[profile.dev]
codegen-units = 8
debug = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
