[package]
name = "flowgger"
version = "0.2.3"
authors = ["Frank Denis <github@pureftpd.org>"]
build = "build.rs"

[features]
capnp-recompile = ["capnpc"]
cargo-clippy = ["clippy"]
coroutines = ["coio"]
ecdh = ["openssl/ecdh_auto"]
without_kafka = [ ]

default = ["kafka"]

[build-dependencies.capnpc]
version = "*"
optional = true

[dependencies]
capnp = "*"
chrono = "*"
log = "*"
rand = "*"
redis = "*"
serde = "*"
serde_json = "*"
toml = "*"
flate2 = "*"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"
optional = true

[dependencies.coio]
git = "https://github.com/zonyitoo/coio-rs"
optional = true

[dependencies.kafka]
git = "https://github.com/jedisct1/kafka-rust"
branch = "openssl-0.8"
features = ["snappy", "gzip"]
optional = true

[dependencies.openssl]
version = "0.8"
features = ["tlsv1_2", "tlsv1_1", "dh_from_params"]

[profile.dev]
codegen-units = 8
debug = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = "abort"
