[package]
name = "flowgger"
version = "0.1.7"
authors = ["Frank Denis <github@pureftpd.org>"]
build = "build.rs"

[features]
ecdh = ["openssl/ecdh_auto"]
coroutines = ["coio"]

[build-dependencies]
capnpc = "*"

[dependencies]
capnp = "*"
chrono = "*"
log = "*"
redis = "*"
serde = "*"
serde_json = "*"
toml = "*"

[dependencies.coio]
git = "https://github.com/jedisct1/coio-rs.git"
optional = true

[dependencies.kafka]
git = "https://github.com/jedisct1/kafka-rust.git"

[dependencies.openssl]
git = "https://github.com/jedisct1/rust-openssl.git"
features = ["tlsv1_2", "tlsv1_1"]

[profile.dev]
codegen-units = 8
debug = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
