###################
#  Input section  #
###################

[input]

### Syslog over TCP
type = "tcp"
listen = "0.0.0.0:514"
timeout = 3600

### Syslog over TCP, using coroutines
# type = "tcp_co"
# listen = "0.0.0.0:514"
# tcp_threads = 1

### Syslog over TLS
# type = "tls"
# listen = "0.0.0.0:6514"
# framing = "line"
# timeout = 3600
# tls_cert = "flowgger.pem"
# tls_key = "flowgger.pem"
# tls_ca_file = "flowgger.pem"
# tls_method = "TLSv1.2"
# tls_verify_peer = false
# tls_compression = false
# tls_ciphers = "EECDH+AES128:EECDH+CHACHA20:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;";

### Syslog over TLS, using coroutines
# type = "tls_co"
# listen = "0.0.0.0:6514"
# framing = "line"
# tls_threads = 1
# tls_cert = "flowgger.pem"
# tls_key = "flowgger.pem"
# tls_ca_file = "flowgger.pem"
# tls_method = "TLSv1.2"
# tls_verify_peer = false
# tls_compression = false
# tls_ciphers = "EECDH+AES128:EECDH+CHACHA20:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;";

### Redis client
# type = "redis"
# redis_connect = "127.0.0.1"
# redis_queue_key = "logs"
# redis_threads = 1

### Input format and parameters
# format = "ltsv"
# queuesize = 1000000
# [input.ltsv_schema]
# counter = "u64"

####################
#  Output section  #
####################

[output]

### Debug output
type = "debug"

### Kafka output
# type = "kafka"
# kafka_brokers = [ "172.16.205.129:9092" ]
# kafka_topic = "test"
# kafka_threads = 1
# kafka_coalesce = 1000
# kafka_timeout = 60000
# kafka_acks = 0

### Output format and parameters
format = "gelf"
# [output.gelf_extra]
# x-header1 = "x-header1 value"
# x-header2 = "x-header2 value"
