[input]
type = "syslog-tcp"
listen = "0.0.0.0:6514"
format = "rfc5424"
tls_cert = "flowgger.pem"
tls_key = "flowgger.pem"
queuesize = 1000000

[output]
type = "kafka"
format = "gelf"
kafka_brokers = [ "192.168.59.103:9092" ]
kafka_topic = "test"
kafka_threads = 1
kafka_timeout = 60

[output.gelf_extra]
x-header1 = "zok"
x-header2 = "zik"
